---
server:
  port: 2600

o2:
  ui:
    map:
      baseMaps:
        - layerType: "tilewms"
          title: "OSM Bright"
          url: "https://omar-dev.ossim.io/service-proxy/wmsProxy"
          params:
            layers: "o2-basemap-bright"
            format: "image/jpeg"
          options:
            visible: true
      overlayLayers:
        - layerType: "tilewms"
          title: "GeoScript"
          url: "http://localhost:2601/getTile"
          params:
            filter: ""
            version: "1.3.0"
            layers: ""
            styles: ""
            format: "image/png"
          options:
            visible: true


